"""empty message

Revision ID: 12593336c8e9
Revises: a0b4f64d063d
Create Date: 2025-04-11 02:58:55.995828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12593336c8e9'
down_revision = 'a0b4f64d063d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FavoritesStarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starships_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites_starships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_starships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starships_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], name='favorites_starships_starships_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_starships_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_starships_pkey')
    )
    op.drop_table('FavoritesStarships')
    # ### end Alembic commands ###
